name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json5
          sparse-checkout-cone-mode: false
          
      # Run Auto-labeler    
      - name: Assign Labels
        uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Fetch updated issue details
      - name: Fetch Updated Issue Details
        id: get_issue
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
     
      # Get Labels Count
      - name: Get labels from issue
        id: get_labels
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels")
          LABELS_COUNT=$(echo "$response" | jq length)
          echo "LABELS_COUNT=$LABELS_COUNT" >> $GITHUB_ENV

      # Check label count
      - name: Check Label Count
        id: check_label_count
        run: |
          echo "Labels count is: $LABELS_COUNT"
          if [ "$LABELS_COUNT" -gt 0 ]; then
            echo "labels_set=true" >> $GITHUB_ENV
          else
            echo "labels_set=false" >> $GITHUB_ENV
          fi
          echo "labels_set is: $env.labels_set"

      # Close the issue    
      - name: Close Issue
        if: ${{ env.labels_set == 'true' }}
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          headers: '{"accept":"application/vnd.github+json"}'
          data: |
            {
              "state": "closed"
            }
          token: ${{ secrets.GITHUB_TOKEN }}
