name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json5
          sparse-checkout-cone-mode: false
          
      # Run Auto-labeler    
      - name: Assign Labels
        uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Fetch updated issue details
      - name: Fetch Updated Issue Details
        id: get_issue
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Count new labels
      - name: Get Label Count
        id: get_label_count
        run: |
          echo "${{ steps.get_issue.outputs.data }}" | sed -E 's#(https?://[^,{} \n]+)#"\1"#g' > issue_data.json
          cat issue_data.json
          LABELS_COUNT=$(jq '.labels | length' issue_data.json)
        #echo $LABELS_COUNT

      # Check labels added isnt 0
      - name: Check Label Count
        id: check_label_count
        run: |
          if [ "$LABELS_COUNT" -eq 0 ]; then
          echo "labels_set=false" >> $GITHUB_ENV
          else
            echo "labels_set=true" >> $GITHUB_ENV
          fi

      # Close the issue    
      - name: Close Issue
        if: env.labels_set == 'true'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          headers: '{"accept":"application/vnd.github+json"}'
          data: |
            {
              "state": "closed"
            }
          token: ${{ secrets.GITHUB_TOKEN }}
