name: Labeling new issue
on:
  issues:
    types: ['opened','edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json5
          sparse-checkout-cone-mode: false
          
      # Run Auto-labeler    
      - name: Assign Labels
        uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Fetch updated issue details
      - name: Fetch Updated Issue Details
        id: get_issue
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Get labels from issue and filter out excluded labels
      - name: Get Filtered Label Count
        id: get_labels
        run: |
          cd .github/workflows
          ls -a
          EXCLUDED_LABELS=$(cat .github/workflows/excluded_labels)
          LABELS_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
            | jq --argjson excluded "$EXCLUDED_LABELS" \
            '[.labels[] | select(.name as $n | $excluded | index($n) | not) | .name] | length')
          echo "LABELS_COUNT=$LABELS_COUNT" >> $GITHUB_ENV

      # Check label count
      - name: Check Label Count
        id: check_label_count
        run: |
          echo "Labels count is: $LABELS_COUNT"
          if [ "$LABELS_COUNT" -gt 0 ]; then
            echo "LABELS_SET=true" >> $GITHUB_ENV
          else
            echo "LABELS_SET=false" >> $GITHUB_ENV
          fi

      - name: Debug-labelset
        run: |
          echo "LABELS_SET is: $LABELS_SET"

      # Close the issue    
      - name: Close Issue
        if: ${{ env.LABELS_SET == 'true' }}
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          headers: '{"accept":"application/vnd.github+json"}'
          data: |
            {
              "state": "closed"
            }
          token: ${{ secrets.GITHUB_TOKEN }}
