name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      #Checkout Repo
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json5
          sparse-checkout-cone-mode: false
          
      #Run Auto-labeler    
      - uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 3: Fetch updated issue details
      - id: get_issue
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      #Check if a label was added
      - id: check_labels
        run: |
          echo "Labels: ${{ steps.get_issue.outputs.data }}"
          LABELS_COUNT=$(echo '${{ steps.get_issue.outputs.data }}' | jq '.labels | length')
          if [ "$LABELS_COUNT" -eq 0 ]; then
            echo "labels_set=false" >> $GITHUB_ENV
          else
            echo "labels_set=true" >> $GITHUB_ENV
          fi

      #Close the issue    
      - if: env.labels_set == 'true'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          headers: '{"accept":"application/vnd.github+json"}'
          data: |
            {
              "state": "closed"
            }
          token: ${{ secrets.GITHUB_TOKEN }}
