name: Goose_test
on:
   issues:
      types: ['opened','edited']

permissions:
   contents: write
   pull-requests: write
   issues: write

env:
   ISSUE_NUMBER: ${{ github.event.issue.number }}
   PR_NUMBER: ${{ github.event.pull_request.number }}
   GH_TOKEN: ${{ github.token }}
   REPOSITORY: ${{ github.repository }}
   OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}

jobs:
   goose-comment:
      runs-on: self-hosted
      steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            

            - name: Run Goose with github extension
              run: |
                  source ~/.bashrc
                  goose run --with-extension "GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.PAT }} npx -y @modelcontextprotocol/server-github" --instructions $HOME/devdapp-bot/instruction-file/auto_label.md
